---
title: "Running function tests"
---

Although the unit of testing is the function, for organisational purposes, the tests are grouped by package. This is because the tests are run in the context of the package, and eases the process of running and reporting tests.

Tests are run via the `test` function in the `validation` package:

```{r}
#| echo: false
options(repos = c(
  CRAN = "https://cloud.r-project.org"
))
```


```{r}
#| eval: false
#| label: test
validation::test("accrualPlot")
```

The function will download the testing files from GitHub, run the tests and format the results for easier copy/pasting into a reporting issue on GitHub.

```{r}
#| label: test
#| eval: true
#| echo: false
```

:::{.callout-note}
It may be that the package being tested, or indeed functions in the testing infrastructure (`testthat` and `waldo`) have been updated since the tests were authored. This may lead to tests failing that previously passed. In this case, the tests should be updated to reflect the new behaviour.

One particular case is a change in attributes. For example, the `coef` method for a model object returns a named vector, but we might compare the individual coeffients to a vector of expected values. There is thus a potential mismatch in the attributes of the two vectors, which may cause the test to fail with a `names for target but not for current` message. Use of the third edition of `testthat` (v3.0.0) should help to avoid this issue.
:::

